###
GET http://localhost:3000/superDB

###

POST http://localhost:3000/heroes/
Content-Type: application/json

{
    "superName": "batman",
    "realName": "Bruce Wayne",
    "superpower": "stealth",
    "powerLevel": 10,
    "secretIdentity": true
}

###

PUT http://localhost:3000/heroes/1759966731415/
Content-Type: application/json

{
    "superName": "aqua man",
    "realName": "idk",
    "superpower": "swim",
    "powerLevel": 10,
    "secretIdentity": false
}

###

GET http://localhost:3000/

###

DELETE http://localhost:3000/heroes/1759966731415